(cl:in-package clover-srv)
(cl:export '(FRAME_ID-VAL
          FRAME_ID
          FRAME_ID-VAL
          FRAME_ID
          CONNECTED-VAL
          CONNECTED
          ARMED-VAL
          ARMED
          MODE-VAL
          MODE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ROLL_RATE-VAL
          ROLL_RATE
          PITCH_RATE-VAL
          PITCH_RATE
          YAW_RATE-VAL
          YAW_RATE
          VOLTAGE-VAL
          VOLTAGE
          CELL_VOLTAGE-VAL
          CELL_VOLTAGE
))