// Generated by gencpp from file aruco_pose/SetMarkers.msg
// DO NOT EDIT!


#ifndef ARUCO_POSE_MESSAGE_SETMARKERS_H
#define ARUCO_POSE_MESSAGE_SETMARKERS_H

#include <ros/service_traits.h>


#include <aruco_pose/SetMarkersRequest.h>
#include <aruco_pose/SetMarkersResponse.h>


namespace aruco_pose
{

struct SetMarkers
{

typedef SetMarkersRequest Request;
typedef SetMarkersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMarkers
} // namespace aruco_pose


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aruco_pose::SetMarkers > {
  static const char* value()
  {
    return "d6e97b92668530c96251237967755989";
  }

  static const char* value(const ::aruco_pose::SetMarkers&) { return value(); }
};

template<>
struct DataType< ::aruco_pose::SetMarkers > {
  static const char* value()
  {
    return "aruco_pose/SetMarkers";
  }

  static const char* value(const ::aruco_pose::SetMarkers&) { return value(); }
};


// service_traits::MD5Sum< ::aruco_pose::SetMarkersRequest> should match
// service_traits::MD5Sum< ::aruco_pose::SetMarkers >
template<>
struct MD5Sum< ::aruco_pose::SetMarkersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_pose::SetMarkers >::value();
  }
  static const char* value(const ::aruco_pose::SetMarkersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_pose::SetMarkersRequest> should match
// service_traits::DataType< ::aruco_pose::SetMarkers >
template<>
struct DataType< ::aruco_pose::SetMarkersRequest>
{
  static const char* value()
  {
    return DataType< ::aruco_pose::SetMarkers >::value();
  }
  static const char* value(const ::aruco_pose::SetMarkersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aruco_pose::SetMarkersResponse> should match
// service_traits::MD5Sum< ::aruco_pose::SetMarkers >
template<>
struct MD5Sum< ::aruco_pose::SetMarkersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_pose::SetMarkers >::value();
  }
  static const char* value(const ::aruco_pose::SetMarkersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_pose::SetMarkersResponse> should match
// service_traits::DataType< ::aruco_pose::SetMarkers >
template<>
struct DataType< ::aruco_pose::SetMarkersResponse>
{
  static const char* value()
  {
    return DataType< ::aruco_pose::SetMarkers >::value();
  }
  static const char* value(const ::aruco_pose::SetMarkersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARUCO_POSE_MESSAGE_SETMARKERS_H
