// Generated by gencpp from file aruco_pose/SetMarkersResponse.msg
// DO NOT EDIT!


#ifndef ARUCO_POSE_MESSAGE_SETMARKERSRESPONSE_H
#define ARUCO_POSE_MESSAGE_SETMARKERSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_pose
{
template <class ContainerAllocator>
struct SetMarkersResponse_
{
  typedef SetMarkersResponse_<ContainerAllocator> Type;

  SetMarkersResponse_()
    : success(false)
    , message()  {
    }
  SetMarkersResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetMarkersResponse_

typedef ::aruco_pose::SetMarkersResponse_<std::allocator<void> > SetMarkersResponse;

typedef boost::shared_ptr< ::aruco_pose::SetMarkersResponse > SetMarkersResponsePtr;
typedef boost::shared_ptr< ::aruco_pose::SetMarkersResponse const> SetMarkersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_pose::SetMarkersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aruco_pose::SetMarkersResponse_<ContainerAllocator1> & lhs, const ::aruco_pose::SetMarkersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aruco_pose::SetMarkersResponse_<ContainerAllocator1> & lhs, const ::aruco_pose::SetMarkersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aruco_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::aruco_pose::SetMarkersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_pose/SetMarkersResponse";
  }

  static const char* value(const ::aruco_pose::SetMarkersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::aruco_pose::SetMarkersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMarkersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_pose::SetMarkersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_pose::SetMarkersResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_POSE_MESSAGE_SETMARKERSRESPONSE_H
