(cl:in-package clover-msg)
(cl:export '(MODE-VAL
          MODE
          YAW_MODE-VAL
          YAW_MODE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          SPEED-VAL
          SPEED
          LAT-VAL
          LAT
          LON-VAL
          LON
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ROLL_RATE-VAL
          ROLL_RATE
          PITCH_RATE-VAL
          PITCH_RATE
          YAW_RATE-VAL
          YAW_RATE
          THRUST-VAL
          THRUST
          XY_FRAME_ID-VAL
          XY_FRAME_ID
          Z_FRAME_ID-VAL
          Z_FRAME_ID
          YAW_FRAME_ID-VAL
          YAW_FRAME_ID
))