// Generated by gencpp from file clover/SetYawRate.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETYAWRATE_H
#define CLOVER_MESSAGE_SETYAWRATE_H

#include <ros/service_traits.h>


#include <clover/SetYawRateRequest.h>
#include <clover/SetYawRateResponse.h>


namespace clover
{

struct SetYawRate
{

typedef SetYawRateRequest Request;
typedef SetYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetYawRate
} // namespace clover


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clover::SetYawRate > {
  static const char* value()
  {
    return "e84dd53db872d0c7a7d675a20e28c95f";
  }

  static const char* value(const ::clover::SetYawRate&) { return value(); }
};

template<>
struct DataType< ::clover::SetYawRate > {
  static const char* value()
  {
    return "clover/SetYawRate";
  }

  static const char* value(const ::clover::SetYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::clover::SetYawRateRequest> should match
// service_traits::MD5Sum< ::clover::SetYawRate >
template<>
struct MD5Sum< ::clover::SetYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetYawRate >::value();
  }
  static const char* value(const ::clover::SetYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetYawRateRequest> should match
// service_traits::DataType< ::clover::SetYawRate >
template<>
struct DataType< ::clover::SetYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::clover::SetYawRate >::value();
  }
  static const char* value(const ::clover::SetYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clover::SetYawRateResponse> should match
// service_traits::MD5Sum< ::clover::SetYawRate >
template<>
struct MD5Sum< ::clover::SetYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clover::SetYawRate >::value();
  }
  static const char* value(const ::clover::SetYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clover::SetYawRateResponse> should match
// service_traits::DataType< ::clover::SetYawRate >
template<>
struct DataType< ::clover::SetYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::clover::SetYawRate >::value();
  }
  static const char* value(const ::clover::SetYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLOVER_MESSAGE_SETYAWRATE_H
