// Generated by gencpp from file clover/SetYawRateRequest.msg
// DO NOT EDIT!


#ifndef CLOVER_MESSAGE_SETYAWRATEREQUEST_H
#define CLOVER_MESSAGE_SETYAWRATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clover
{
template <class ContainerAllocator>
struct SetYawRateRequest_
{
  typedef SetYawRateRequest_<ContainerAllocator> Type;

  SetYawRateRequest_()
    : yaw_rate(0.0)  {
    }
  SetYawRateRequest_(const ContainerAllocator& _alloc)
    : yaw_rate(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_rate_type;
  _yaw_rate_type yaw_rate;





  typedef boost::shared_ptr< ::clover::SetYawRateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clover::SetYawRateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetYawRateRequest_

typedef ::clover::SetYawRateRequest_<std::allocator<void> > SetYawRateRequest;

typedef boost::shared_ptr< ::clover::SetYawRateRequest > SetYawRateRequestPtr;
typedef boost::shared_ptr< ::clover::SetYawRateRequest const> SetYawRateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clover::SetYawRateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clover::SetYawRateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::clover::SetYawRateRequest_<ContainerAllocator1> & lhs, const ::clover::SetYawRateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.yaw_rate == rhs.yaw_rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::clover::SetYawRateRequest_<ContainerAllocator1> & lhs, const ::clover::SetYawRateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace clover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::clover::SetYawRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clover::SetYawRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover::SetYawRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clover::SetYawRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover::SetYawRateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clover::SetYawRateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clover::SetYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf7d0742e75dc32cdd65763b118b5bf4";
  }

  static const char* value(const ::clover::SetYawRateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf7d0742e75dc32cULL;
  static const uint64_t static_value2 = 0xdd65763b118b5bf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::clover::SetYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clover/SetYawRateRequest";
  }

  static const char* value(const ::clover::SetYawRateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clover::SetYawRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw_rate\n"
;
  }

  static const char* value(const ::clover::SetYawRateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clover::SetYawRateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetYawRateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clover::SetYawRateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clover::SetYawRateRequest_<ContainerAllocator>& v)
  {
    s << indent << "yaw_rate: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLOVER_MESSAGE_SETYAWRATEREQUEST_H
